# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

updates:
  # Configuration for npm dependencies
  - package-ecosystem: "npm" # Specifies npm as the package manager
    directory: "/"           # The directory containing your package.json
    schedule:
      interval: "daily"      # Checks for updates daily
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 5 # Maximum open PRs for npm updates
    ignore:
      - dependency-name: "*" # Applies rules to all dependencies
        update-types:
          - "version-update:semver-major" # Ignore major version updates
          
  - package-ecosystem: "composer" # Specifies npm as the package manager
    directory: "/"           # The directory containing your package.json
    schedule:
      interval: "daily"      # Checks for updates daily
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 5 # Maximum open PRs for npm updates
    ignore:
      - dependency-name: "*" # Applies rules to all dependencies
        update-types:
          - "version-update:semver-major" # Ignore major version updates
          
  - package-ecosystem: "github-actions" # Specifies npm as the package manager
    directory: "/"           # The directory containing your package.json
    schedule:
      interval: "daily"      # Checks for updates daily
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 5 # Maximum open PRs for npm updates
    ignore:
      - dependency-name: "*" # Applies rules to all dependencies
        update-types:
          - "version-update:semver-major" # Ignore major version updates
